---

require:
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**'

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
