---

require:
  - rubocop-rake
  # - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/**'

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
